import Svgs from "@/components/common/Svgs";
import "react-tooltip/dist/react-tooltip.css";
import "../../public/assets/css/plugins/swiper.min.css";
import "../../public/assets/sass/style.scss";
import "rc-slider/assets/index.css";
import "tippy.js/dist/tippy.css";
import LoginFormPopup from "@/components/common/LoginFormPopup";
// import { useEffect } from "react";
import ScrollTop from "@/components/common/ScrollTop";
import Context from "@/context/Context";
import { MenuProvider } from "@/context/MenuContext";
import { UserProvider } from "@/context/UserContext";
// import QuickView from "@/components/modals/QuickView";
import CartDrawerWithoutTrans from "@/components/shopCartandCheckout/CartDrawerWithoutTrans";
import SiteMap from "@/components/modals/SiteMap";
import NewsLetter from "@/components/modals/NewsLetter";
// import CookieContainer from "@/components/common/CookieContainer";
import MobileHeaderWithoutTrans from "@/components/headers/MobileHeaderWithoutTrans";
import SizeGuide from "@/components/modals/SizeGuide";
import Delivery from "@/components/modals/Delivery";
import CustomerLoginWithoutTrans from "@/components/asides/CustomerLoginWithoutTrans";
import ShopFilter from "@/components/asides/ShopFilter";
import ProductDescription from "@/components/asides/ProductDescription";
import ProductAdditionalInformation from "@/components/asides/ProductAdditionalInformation";
import ProductReviews from "@/components/asides/ProductReviews";
import MobileFooterWithoutTrans from "@/components/footers/MobileFooterWithoutTrans";
import localFont from "next/font/local";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';

const myFont = localFont({
  src: "../../public/assets/fonts/wulkan/WulkanDisplayRegular.ttf",
});

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
      <Svgs />
        <Context>
          <UserProvider>
            <MenuProvider>
              <MobileHeaderWithoutTrans />
                {children}
              <MobileFooterWithoutTrans />
              {/* //modals and asides */}
              <LoginFormPopup />
              {/* <QuickView /> */}
              {/* <NewsLetter /> */}
              {/* <CookieContainer /> */}
              <SizeGuide />
              <Delivery />
              <CartDrawerWithoutTrans />
              <SiteMap />
              <CustomerLoginWithoutTrans />
              {/* <ShopFilter /> */}
              <ProductDescription />
              <ProductAdditionalInformation />
              {/* <ProductReviews /> */}
            </MenuProvider>
          </UserProvider>
        </Context>
        <div className="page-overlay" id="pageOverlay"></div>
        <ScrollTop />
      </body>
    </html>
  )
}
